- Makefile
This is causing jenkins to fail.
> Fixed branches names

- templates/cakephp/deprecated.latte
> make sections names more visible

- templates/cakephp/class.latte
Refs https://github.com/cakephp/cakephp-api-docs/pull/28#issuecomment-108552955
> No summary

- templates/cakephp/class.latte
- templates/cakephp/css/style.css
> Add permalink for class methods and properties

- Makefile
closes #32 by adding 2.7 version on build
> add build against 2.7

- templates/cakephp/csf-navbar.latte
> add 2.7 link in navbar

- templates/cakephp/config.neon
> 3.2 doesn't show up in the menu

- Makefile
> 3.2 has been released and is now master

- .dockerignore
- .gitignore
- Dockerfile
- nginx.conf
Fewer things in the jenkins job is A+
> Add docker config from jenkins job

- templates/cakephp/resources/css/styles.css
- templates/cakephp/source.latte
> add code syntax coloration

- templates/cakephp/js/main.js
fixes #51 
I also change the indentation to be consistent in a separate commit to ease review
> Correctly scroll to the source code line position

- Makefile
it's a hack but  the --exclude option seems to be buggy in Apigen and this would work for now
> update the excluded path

- templates/cakephp/header.latte
and do not use $annotation variable it triggers a warning
> fix broken link

- templates/cakephp/resources/css/styles.css
to looks like the book and the code source display
from
to
> remove bold in code sample

- Makefile
- apigen.neon
follows #71
I didn't change 1.x as the result was weird I don't know anything about this version
> restore the tree in the sidebar for 2.X

- jenkins.groovy
I'm not at all confident this works, but it at least captures the existing build config in something resembling a job definition.
> Import existing build definition into jenkins DSL

- apigen.neon
- templates/cakephp/header.latte
ref #78 This feature is broken, and won't be fixed upstream.
ApiGen decided to remove this feature totally
https://github.com/ApiGen/ApiGen/pull/790
> Remove download button

- templates/cakephp/js/main.js
> Enable anchor of submenu and megamenu.

- templates/cakephp/js/main.js
- templates/cakephp/resources/css/styles.css
> Make search results usable on phones/tablets.

- templates/cakephp/header.latte
> Sync header links with cakephp.org

- Makefile
Generate chronos 1.0 and 1.1 docs at the same time.
Refs #93
> Add chronos 1.1 docs

- templates/cakephp/footer.latte
It is going away very soon. See cakephp/cakephp.org#122
> Remove google+

- templates/cakephp/footer.latte
- templates/cakephp/resources/css/responsive.css
fix issue https://github.com/cakephp/cakephp-api-docs/issues/114
> sync social block
